### ISSUE TITLE
Install error on MAC

### ISSUE THREAD

**Issue by linyunhe** [JohnLangford/vowpal_wabbit#1426]
I'm trying to install this on MAC with anaconda. I have fixed all things as README said but still run into two errors:

"fatal error: 'boost/foreach.hpp' file not found" and "fatal error: 'boost/program_options.hpp' file not found".

Does someone know what's going on about these two errors?

Thank you so much!

**Comment by MLWave** [comment]
Did you install `boost`, `libboost`, `boost-python`? It seems some essential boost files are not found/have correct path.

**Comment by linyunhe** [comment]
I did. I have no idea why the program_options file is missing.

**Comment by MLWave** [comment]
Also no idea. You could try: https://github.com/JohnLangford/vowpal_wabbit/issues/1364

Which refers to: https://github.com/JohnLangford/vowpal_wabbit/issues/1095#issuecomment-330327771
https://github.com/JohnLangford/vowpal_wabbit/issues/723#issuecomment-121450482

**Comment by arielf** [comment]
The standard/normal location (on Ubuntu/Debian) of your missing file is:
```
/usr/include/boost/program_options.hpp
```
On Mac it may be in a different, less standard location.  Depending on whether you use `Mac ports`, `brew` or whatever `anaconda` insists on.

As @MLWave hinted, you should verify that it is there.
 
If not, you may have `libboost-dev` (or the equivalent Mac ports or brew -- whichever you or anaconda is using -- package) missing.

Also note that installing `libboost` may not be enough.  You need `libboost-dev` for full headers.

If you believe you do have it installed, you may:

- Try `find` or `locate` to find the exact non-standard location where it is installed.
- Share that location here so the `Makefile`s can be improved to cover more cases
-  Make sure that your C++ compiler is looking for files in that location by adding
`-I /the/missing/location` to compiler flags via the `Makefile`s `BOOST_INCLUDE` variable definition inside the:
```
  ifeq ($(UNAME), Darwin)
```
clauses.

Also see the comments in the `Makefile`s regarding Mac OS-X envs.

**Comment by linyunhe** [comment]
Thank you for your suggestions. 

I do have this file under 
"/usr/MYUSERNAME/anaconda3/include/boost/program_options.hpp". 

However according to the README, the include and lib folder when installing should be (in Makefile) 
"/usr/MYUSERNAME/anaconda3/envs/vw/include" and "/usr/MYUSERNAME/anaconda3/envs/vw/lib". 
But I didn't find this program_options.hpp file under this  include folder.

After I changing them to "anaconda3/include" and "anaconda3/lib" (plus adding
-I /the/missing/location), I can still get this error.

Moreover, I have fixed the setup.py under python folder for this compile since at first it cannot find_library for "boost_python-mt" or "boost_python3-mt" for Darwin system (MAC I'm using). But it works if I changed "boost_python3-mt" to "boost_python3" (because names changed). I thought it isn't related to the error now I'm running into right?

**Comment by arielf** [comment]
Hi @linyunhe

Glad you figured out a way (?) to make it work.

vowpal-wabbit has no simple way to guess that a standard boost file is placed in such a non-standard directory.

`boost_python3-mt` and `boost_python3` are just two implementations of the boost library.  They provide the same API. `mt` stands for "multi-threaded".  If your app is multi-threaded (`vw` is) you should be linking with the `mt` version for thread-safety.  I'm not sure if anaconda cares about this.

Maybe you should open these issues with anaconda?   There's a history of people having similar issues with this distribution.  Anaconda seems to live in its own world so it doesn't play nice with standard-behaving code.  This is the core issue.  It is not really a vowpal-wabbit issue.  A standard python installation should work fine with `vw`.

**Comment by JohnLangford** [comment]
All the boost program options code happens to be run in a single thread so I expect thread-safety itself is not actually required.  On other hand, the code is not performance sensitive, so I see no real drawback to using the -mt library either.

I'm assuming(?) that this is fixed, and closing for now.  Please reopen if needed.

**Comment by gwerbin** [comment]
For anyone still having an issue with Conda, I was able to build VW on Linux as follows:

```bash
# Make a clean environment with Python and some common packages
conda create -p ./test-env python=3.6 numpy scipy scikit-learn pandas gensim mkl
conda activate ./test-env

# Install:
#  - dependencies
#  - a compiler that can handle recent C++ standard, and the stdlib to go with it
conda install -c pkgs/main zlib libboost boost-cpp boost "gcc_linux-64>5" "gxx_linux-64>5" libstdcxx-ng

export BOOST_ROOT="${CONDA_PREFIX}/include/boost"
export LDFLAGS="-L${CONDA_PREFIX}/lib"
export CPPFLAGS="-I${CONDA_PREFIX}/include"
./autogen.sh --prefix="${CONDA_PREFIX}" --with-boost-libdir="${conda_env}/lib"
make
make install
```

Not sure how easily this can be translated into a Conda recipe. You might be able to copy and paste that right into `build.sh`,

**Comment by liyinan1001** [comment]
> For anyone still having an issue with Conda, I was able to build VW on Linux as follows:
> 
> ```shell
> # Make a clean environment with Python and some common packages
> conda create -p ./test-env python=3.6 numpy scipy scikit-learn pandas gensim mkl
> conda activate ./test-env
> 
> # Install:
> #  - dependencies
> #  - a compiler that can handle recent C++ standard, and the stdlib to go with it
> conda install -c pkgs/main zlib libboost boost-cpp boost "gcc_linux-64>5" "gxx_linux-64>5" libstdcxx-ng
> 
> export BOOST_ROOT="${CONDA_PREFIX}/include/boost"
> export LDFLAGS="-L${CONDA_PREFIX}/lib"
> export CPPFLAGS="-I${CONDA_PREFIX}/include"
> ./autogen.sh --prefix="${CONDA_PREFIX}" --with-boost-libdir="${conda_env}/lib"
> make
> make install
> ```
> 
> Not sure how easily this can be translated into a Conda recipe. You might be able to copy and paste that right into `build.sh`.
> 
> Edit:
> 
> Conda recipe for Linux: https://gist.github.com/gwerbin/f8b49bf5f430edaa5a8cfdf7e515ae70
> 
> Not sure if anything will need to be adapted for MacOS

Hi gwerbin, where is autogen.sh? It's not in vw project folder

**Comment by jackgerrits** [comment]
Autogen is no longer used for building, we've migrated over to CMake. I haven't tested this but CMake has a similar prefix path arg: `cmake -D CMAKE_PREFIX_PATH=/path/to/custom/location`
